### PR TITLE
Added Projects and Tasks SDK

### PR DESCRIPTION
**Pull request by scott-jackman**
@rswingler please review

### CODE REVIEW

**Comment by rswingler** [comment]
@scott-jackman +1 Looks great. Would it be possible to add some "example" files? Each of the other clients feature example references: https://github.com/domoinc/domo-java-sdk/tree/master/domo-java-sdk-all/src/test/java/com/domo/sdk/users

**Review by checketts — APPROVED** [review]
Thanks! Looks good!  The only thing that stood out to me was that the haahcode for projects and projectlist were generated using different techniques. I can't recall how other models do it (phone review)

**Comment by scott-jackman** [comment]
@rswingler  Jason added the example files. If these work, please merge.

**Comment by rswingler** [comment]
+1

**Pull request merged**
